apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  namespace: idp-platform
  labels:
    app: ai-agent
    component: diagnostics
    part-of: idp-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
        component: diagnostics
    spec:
      serviceAccountName: ai-agent
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: ai-agent
          image: ai-agent:latest # Replaced by Kustomize overlay or ArgoCD
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-agent-secrets
                  key: google-api-key
            - name: LOG_LEVEL
              value: "INFO"
            - name: CORS_ORIGINS
              value: "https://portal.idp-platform.internal"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  namespace: idp-platform
  labels:
    app: ai-agent
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: ai-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-agent
  namespace: idp-platform
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::role/idp-ai-agent-irsa"
  labels:
    app: ai-agent
